name = "TimeCorrelations"
uuid = "cf596c4a-4b9f-4035-8749-0c233c327923"
authors = ["Jack Toppen"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
